### ISSUE TITLE
Link to API documentation

### ISSUE THREAD

**Issue by mernst** [carrotsearch/hppc#18]
At 
https://github.com/carrotsearch/hppc/wiki/API-Overview
the link with anchor text "JavaDocs of each release" does not link to API documentation as I would expect.

HPPC has good a API overview, but it is not easy to find from https://github.com/carrotsearch/hppc or https://github.com/carrotsearch/hppc/wiki.

I suggest there should be a link from the wiki to https://carrotsearch.github.io/hppc/releases/0.7.0/api/overview-summary.html or preferably to API documentation for a more recent release (0.8.2).

**Comment by dweiss** [comment]
These links were part of the release page, which I removed in favor of github releases... But you're right that they were out of date  - they should be part of each release notes much like it is here:
https://github.com/carrot2/carrot2/releases/tag/release%2F4.2.1

I'll try to upload them in a spare moment.

**Comment by dweiss** [comment]
I've added API links to releases. I think it's sufficient (and easier to maintain than the wiki).
