### ISSUE TITLE
OSGi metadata in JAR manifest (BND) [HPPC-182]

### ISSUE THREAD

**Issue by dweiss** [carrotsearch/hppc#224]
I don't use OSGi and I don't know how to do it, but leaving as a placeholder.

---
Issue: HPPC-182 (migrated from JIRA), created by Dawid Weiss (@dweiss), updated Sep 08 2020

**Comment by jest** [comment]
@dweiss Give me some context (probably someone complained about this one), I might help with OSGi-related stuff.

**Comment by dweiss** [comment]
I don't think we've heard about anybody using hppc with osgi so I don't think there's any pressure to do something about it (?). Good to hear from you. ;)

**Comment by dweiss** [comment]
I've read a few posts about the current state of osgi and I honestly don't think it's worth your or my time. Let's just move on.
