### ISSUE TITLE
Bump minimum required Java to 11

### ISSUE THREAD

**Issue by dweiss** [carrotsearch/hppc#239]
Motivated by dependencies (tools and plugins) that need at least Java 11. Anybody still on Java 8?... Seems like ancient history. I think bumping the minimum to 11 seems ok.

**Comment by hugoncosta** [comment]
For reference - a lot of enterprise software still very much depends on JDK8. If not for anything, for the sake of compatibility with other enterprise clients. Unless the move to JDK11+ is a must (feature wise), JDK8 compatibility should remain.

**Comment by dweiss** [comment]
I understand corporate needs but... you know - this is a hobby project... Realistically, I don't think I even have JDK 1.8 anywhere around... I think we'll stick with JDK11 as the minimum. I'm sorry if it adds grit to your workflow.
