### ISSUE TITLE
Methods missing or misleading in list and other containers

### ISSUE THREAD

**Issue by bruno-roustant** [carrotsearch/hppc#242]
While replacing generic structures (Map, Set, List) in Lucene, I noticed a couple of points  that could be improved:

1- KTypeIndexedContainer.remove(int index) is misleading and may provoke sneaky bugs.
When one replaces an existing List of Integer by an IntArrayList, the behavior of this list.remove(int) changes silently. The compilation succeeds (sneaky bug) but List.remove(T element) has not the same semantic as IntArrayList.remove(int index).
Proposal, but breaks the API:
- rename KTypeIndexedContainer.remove(int index) to KTypeIndexedContainer.removeAt(int index).
- add KTypeIndexedContainer.remove(KType e) which delegates to removeFirst(KType e) and returns a boolean.

2- Add KTypeContainer.stream().
Primitive types would return the primitive streams. Very handy when replacing an existing generic List, this can easily be used to compute min, max, etc.

3- Add KTypeArrayList.sort().

**Comment by dweiss** [comment]
Good points! I'm all for it.

**Comment by bruno-roustant** [comment]
Even the API change?
That will probably break some HPPC integration. I don't know how to help on this.

**Comment by dweiss** [comment]
If we release a major version then I think it's fine to break the API - especially if it's already broken... I think it would help if we can remove the remove method entirely and replace it with something else, so that people upgrading will have a compilation error and will have to take a look at why (and what to replace it with).

removeAt sounds good. Maybe removeElement for previous remove?

**Comment by bruno-roustant** [comment]
At first I wanted to keep the same boolean remove(T element) signature to help migrating from a generic list. But actually there is another T remove(int index) in the generic list, so it's error prone.
So, yes, removeElement sounds good as at least there are visible compilation errors easy to adapt.

**Comment by bruno-roustant** [comment]
Also, I see two other potential improvements, please tell me what you think of them:

4- KType removeLast()
To remove the last element. It is present in the generic list, and often called when the list is used in a similar way as a stack.

5- reverse()
I see it called with Collections.reverse() on the generic list. It is also helpful if we want to sort in descending order, as there is no way to sort descending primitives, you have to sort and reverse.

**Comment by dweiss** [comment]
I like both suggestions.

**Comment by dweiss** [comment]
I've done a few cleanups and upgrades here and there. Let me know if you'll have the time to work on the above, @bruno-roustant . I need to switch contexts but I'd love to push it forward and have a proper 0.10.0 release sooner rather than later!

**Comment by dweiss** [comment]
Thank you!

**Comment by bruno-roustant** [comment]
Done.
Thanks Dawid for the feedback!
