### ISSUE TITLE
Cannot build with JDK 11 after the latest build changes.

### ISSUE THREAD

**Issue by bruno-roustant** [carrotsearch/hppc#246]
CHANGES.txt says GH-239: Minimum Java bumped to 11
(but README.md does not mention that)
Actually JDK 11 is not sufficient to build, one needs JDK 17, is it intended?

I updated my master branch to the latest today, then I tried ./gradlew clean test

With JAVA_HOME=$HOME/jdk/zulu11.72.19/
It fails with

> * What went wrong:
> A problem occurred configuring root project 'hppc-root'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not resolve com.carrotsearch.gradle.dependencychecks:gradle-dependencychecks-plugin:0.0.7.
>      Required by:
>          project : > com.carrotsearch.gradle.dependencychecks:com.carrotsearch.gradle.dependencychecks.gradle.plugin:0.0.7
>       > No matching variant of com.carrotsearch.gradle.dependencychecks:gradle-dependencychecks-plugin:0.0.7 was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.7' but:
>           - Variant 'apiElements' declares a library, packaged as a jar, and its dependencies declared externally:
>               - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
>               - Other compatible attribute:
>                   - Doesn't say anything about org.gradle.plugin.api-version (required '8.7')
>           - Variant 'javadocElements' declares a component for use during runtime, and its dependencies declared externally:
>               - Incompatible because this component declares documentation and the consumer needed a library
>               - Other compatible attributes:
>                   - Doesn't say anything about its elements (required them packaged as a jar)
>                   - Doesn't say anything about its target Java version (required compatibility with Java 11)
>                   - Doesn't say anything about org.gradle.plugin.api-version (required '8.7')
>           - Variant 'runtimeElements' declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
>               - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
>               - Other compatible attribute:
>                   - Doesn't say anything about org.gradle.plugin.api-version (required '8.7')
>           - Variant 'sourcesElements' declares a component for use during runtime, and its dependencies declared externally:
>               - Incompatible because this component declares documentation and the consumer needed a library
>               - Other compatible attributes:
>                   - Doesn't say anything about its elements (required them packaged as a jar)
>                   - Doesn't say anything about its target Java version (required compatibility with Java 11)
>                   - Doesn't say anything about org.gradle.plugin.api-version (required '8.7')
> 

With JAVA_HOME=$HOME/jdk/zulu17.50.19/
It passes.

**Comment by dweiss** [comment]
No - it isn't. Give me a sec.

**Comment by dweiss** [comment]
Ok, will work now.
