### ISSUE TITLE
could  provide concurrency security and primitive types map？

### ISSUE THREAD

**Issue by zs121233** [carrotsearch/hppc#38]
our DTO is protoBuffer and long is primitive type.
but we need use primitive type long to get object from map , cause lots of Long.valueof

**Comment by dweiss** [comment]
I don't think I understand your question but use [LongObjectHashMap](http://carrotsearch.github.io/hppc/releases/0.9.1/api/com/carrotsearch/hppc/LongObjectHashMap.html)<VType> or [LongObjectWormMap](http://carrotsearch.github.io/hppc/releases/0.9.1/api/com/carrotsearch/hppc/LongObjectWormMap.html)<VType>.

**Comment by zs121233** [comment]
just like ConcurrentHashMap，but user primitive type long or int？

**Comment by zs121233** [comment]
> I don't think I understand your question but use [LongObjectHashMap](http://carrotsearch.github.io/hppc/releases/0.9.1/api/com/carrotsearch/hppc/LongObjectHashMap.html) or [LongObjectWormMap](http://carrotsearch.github.io/hppc/releases/0.9.1/api/com/carrotsearch/hppc/LongObjectWormMap.html).



> I don't think I understand your question but use [LongObjectHashMap](http://carrotsearch.github.io/hppc/releases/0.9.1/api/com/carrotsearch/hppc/LongObjectHashMap.html) or [LongObjectWormMap](http://carrotsearch.github.io/hppc/releases/0.9.1/api/com/carrotsearch/hppc/LongObjectWormMap.html).
just like ConcurrentHashMap，but user primitive type long or int？

**Comment by zs121233** [comment]
> I don't think I understand your question but use [LongObjectHashMap](http://carrotsearch.github.io/hppc/releases/0.9.1/api/com/carrotsearch/hppc/LongObjectHashMap.html) or [LongObjectWormMap](http://carrotsearch.github.io/hppc/releases/0.9.1/api/com/carrotsearch/hppc/LongObjectWormMap.html).

just like ConcurrentHashMap，but use primitive type long or int？

**Comment by dweiss** [comment]
Oh, I see. No - you can't use HPPC collections for multi-threaded access, sorry. There are no plans to do it.
